"""
KrishiMitra AI — Chat API Route.

POST /api/v1/chat
  Accepts a farmer's question and returns a structured agricultural answer
  powered by IBM Granite + RAG.
"""

from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Request, status

from backend.app.auth.firebase_auth import get_current_user
from backend.app.models.chat import ChatRequest, ChatResponse
from backend.app.utils.logger import get_logger

logger = get_logger(__name__)

router = APIRouter(prefix="/chat", tags=["Chat"])


@router.post(
    "",
    response_model=ChatResponse,
    summary="Ask a farming question",
    description=(
        "Submit an agricultural question in English or Hindi. "
        "Returns a structured answer grounded in the knowledge base, "
        "generated by IBM Granite."
    ),
    status_code=status.HTTP_200_OK,
)
async def chat(
    request_body: ChatRequest,
    request: Request,
    current_user: Optional[dict] = Depends(get_current_user),
) -> ChatResponse:
    """Handle a single chat turn.

    - Validates the incoming question (3–500 chars, non-blank)
    - Optionally verifies Firebase auth token (if provided)
    - Delegates to ChatService for RAG retrieval + Granite generation
    - Returns a structured ChatResponse

    The ChatService and RAGPipeline are stored on app.state by the lifespan
    context manager in main.py — this keeps them as proper singletons.
    """
    chat_service = request.app.state.chat_service

    user_id = current_user.get("uid", "anonymous") if current_user else "anonymous"
    logger.info(
        "POST /chat — question length=%d, language=%s, user=%s",
        len(request_body.question),
        request_body.language,
        user_id,
    )

    try:
        response = chat_service.answer(request_body)
    except Exception as exc:  # noqa: BLE001
        # Catch unexpected errors so the API never returns a 500 with a raw traceback
        logger.exception("Unexpected error in chat handler: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An unexpected error occurred. Please try again.",
        ) from exc

    return response

